Server
MauriceNDS/ft_irc pull request #35
Opened 2022-01-27 14:32 UTC by MauriceNDS

**Server part added !** 

Now we can connect to the server and send requests from multiple clients, enjoy !

2022-01-27 14:54 UTC, SimonCROS requested changes

2022-01-27 14:54 UTC, SimonCROS commented on includes/ft_irc.hpp
> +#include <poll.h>
Move includes to Server.hpp if needed or Server.cpp else.

2022-01-27 14:54 UTC, SimonCROS commented on modules/api/command/CommandManager.cpp
> -		throw CommandNotFoundException();
`CommandNotFoundException` now unused, file can be deleted (check for ohter exceptions if if they are used).

2022-01-27 14:54 UTC, SimonCROS commented on modules/server/Server.cpp
> +	connectionConfig.sin_port = htons(stoi(this->port));
`stoi`: C++11

2022-01-27 14:54 UTC, SimonCROS commented on modules/server/Server.cpp
> +Server::Server(const string& name, const string& port, const string& password) : name(name), port(port), password(password) {
Change `port` from `const string&` to `int` type.
```suggestion
Server::Server(const string& name, int port, const string& password) : name(name), port(port), password(password) {
```

2022-01-27 14:54 UTC, SimonCROS commented on includes/modules/server/Server.hpp
> +	const string port;
Change `port` from `const string` to `const int` type.
```suggestion
	const int port;
```

2022-01-27 14:54 UTC, SimonCROS commented on includes/modules/server/Server.hpp
> +	Server(const string& name, const string& port, const string& password);
Change `port` from `const string&` to `int` type.
```suggestion
	Server(const string& name, int port, const string& password);
```

2022-01-28 10:00 UTC, Owllyy requested changes

2022-01-28 10:00 UTC, Owllyy commented on modules/server/Server.cpp
> +#define MAX_BUFFER_LENGTH 4096
```suggestion
#define MAX_BUFFER_LENGTH 512
```

"these messages SHALL NOT exceed 512 characters in length" RFC 2812

2022-01-28 10:18 UTC, Owllyy approved these changes

2022-01-28 12:32 UTC, SimonCROS requested changes

2022-01-28 12:32 UTC, SimonCROS commented on modules/server/Server.cpp
> +Server::Server(const string& name, const string& port, const string& password) : name(name), password(password) {
```suggestion
Server::Server(const string& name, const int port, const string& password) : name(name), port(port), password(password) {
```

2022-01-28 12:32 UTC, SimonCROS commented on includes/modules/server/Server.hpp
> +	int port;
```suggestion
	const int port;
```

2022-01-28 12:42 UTC, SimonCROS approved these changes

2022-01-28 12:43 UTC, merged