Last command
MauriceNDS/ft_irc pull request #39
Opened 2022-02-07 12:12 UTC by Owllyy

Tout segfault, merci a moi.

2022-02-07 12:34 UTC, SimonCROS commented on includes/modules/core/command/PartCommand.hpp
>          vector<Channel *> channelList = cmd.getArg<vector<Channel *> >("channels");
```suggestion
        vector<Channel *>& channelList = cmd.getArg<vector<Channel *> >("channels");
```

2022-02-07 12:34 UTC, SimonCROS commented on includes/modules/core/command/PartCommand.hpp
> +		vector<Channel *> channelList = cmd.getArg<vector<Channel *> >("channels");
```suggestion
		vector<Channel *>& channelList = cmd.getArg<vector<Channel *> >("channels");
```

2022-02-07 23:56 UTC, SimonCROS commented on modules/api/Connection.cpp
> +
?

2022-02-07 23:56 UTC, SimonCROS commented on includes/modules/core/command/PrivmsgCommand.hpp
> +			(*it)->send(sender.getName() + " :" + message.c_str());
To check with the RFC norme. Each response is supposed to be formatted as a command, so with a prefix and a command/response code.

2022-02-11 16:27 UTC, SimonCROS requested changes

2022-02-11 16:27 UTC, SimonCROS commented on .gitignore
> +INFO
Plus nécessaire

2022-02-11 16:27 UTC, SimonCROS commented on includes/modules/core/command/PrivmsgCommand.hpp
> +					if (!Irc::getInstance().getChannels().find((*it)->getName())->second->isOnChan(static_cast<User *>(&sender)) && Irc::getInstance().getChannels().find((*it)->getName())->second->getFlag().outside
A user variable is already declared.
```suggestion
					if (!Irc::getInstance().getChannels().find((*it)->getName())->second->isOnChan(&user) && Irc::getInstance().getChannels().find((*it)->getName())->second->getFlag().outside_message) {
```

2022-02-11 16:27 UTC, SimonCROS commented on includes/modules/core/command/PrivmsgCommand.hpp
> +		string from = user.getName() + "!" + user.getUserName() + "@" + Irc::getInstance().getServer().getHost();;
Unused
```suggestion
```

2022-02-11 16:27 UTC, SimonCROS commented on includes/modules/core/command/PrivmsgCommand.hpp
> +		User &user = static_cast<User &>(sender);
```suggestion
		User& user = static_cast<User&>(sender);
```

2022-02-11 16:27 UTC, SimonCROS commented on includes/modules/core/command/QuitCommand.hpp
> +					it->second->send(":" + user.getName() + " QUIT :" + user.getName() + "\n");
Responses may be used here.

2022-02-13 08:43 UTC, Owllyy commented on includes/modules/core/command/QuitCommand.hpp
> +					it->second->send(":" + user.getName() + " QUIT :" + user.getName() + "\n");
Bel oublie oups

2022-02-13 19:08 UTC, SimonCROS requested changes
T'as fait un travail excellent @Owllyy (toi aussi @MauriceNDS mais pas sur cette PR 😆) !

2022-02-13 19:08 UTC, SimonCROS commented on includes/modules/core/command/ModeCommand.hpp
> +#endif /* FT_IRC_CORE_MODE_COMMAND */
Newline

2022-02-13 19:08 UTC, SimonCROS commented on includes/modules/core/command/ModeCommand.hpp
> +			if ((*mode)[i] == 'o') {
switch is faster (it uses a binary tree)

Don't use a switch when there is less than 5 cases, because it will be slower than else if

2022-02-13 19:08 UTC, SimonCROS commented on modules/core/Irc.cpp
> +		.argument("modeparams", GenericArguments::optional(GenericArguments::list<string *>(GenericArguments::string())))
Multiple arguments must be accepted, use a custom element

2022-02-14 19:55 UTC, SimonCROS requested changes

2022-02-14 19:55 UTC, SimonCROS commented on includes/modules/core/command/ModeCommand.hpp
> +		std::cout << "OOO" << std::endl;
Debug ?

2022-02-14 19:55 UTC, SimonCROS commented on includes/modules/core/command/ModeCommand.hpp
> +					channel.promoteChanop(server.findUser(i->value));
VoiceOp ?

And why a uppercase on VoiceOp and not on Chanop ?

2022-02-14 19:55 UTC, SimonCROS commented on ooo
> +PASS password
File to remove

2022-02-15 08:35 UTC, MauriceNDS approved these changes
Lucas did increadible

2022-02-17 09:06 UTC, MauriceNDS approved these changes

2022-02-17 09:06 UTC, MauriceNDS commented on includes/modules/core/command/ModeCommand.hpp
> +			case 's': flags.reop = enabled; break;
is this fucked up ?

2022-02-17 09:06 UTC, MauriceNDS commented on includes/modules/core/command/ModeCommand.hpp
> +			case 's': flags.reop = enabled; break;
I'll fix

2022-02-17 09:06 UTC, MauriceNDS commented on includes/modules/core/command/ModeCommand.hpp
> +			case 'o':
Where do we add 'o' and 'v' flag ???

2022-02-23 12:06 UTC, SimonCROS approved these changes

2022-02-23 12:06 UTC, merged